import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ContainerInner, ContainerRoot } from "@shared/ui";

import { Navigation } from "@widgets/navigation";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Navigation />
        <ContainerRoot>
          <ContainerInner>{children}</ContainerInner>
        </ContainerRoot>
      </body>
    </html>
  );
}
