import type { Metadata } from "next";

import { Navigation } from "@widgets/navigation";

import "./globals.css";

export const metadata: Metadata = {
  title: "뉴브랜치",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
