import type { LearningGoalItem } from "./learningGoal.types";

export const LEARNING_GOALS_MOCK: readonly LearningGoalItem[] = [
  {
    id: "goal-1",
    category: "자격증",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 62,
    dDay: 24,
    status: "inProgress",
  },
  {
    id: "goal-2",
    category: "어학",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 21,
    dDay: 24,
    status: "notStarted",
  },
  {
    id: "goal-3",
    category: "시험",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 62,
    dDay: 24,
    status: "imminent",
  },
  {
    id: "goal-4",
    category: "자격증",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 62,
    dDay: 24,
    status: "inProgress",
  },
  {
    id: "goal-5",
    category: "시험",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 62,
    dDay: 24,
    status: "inProgress",
  },
  {
    id: "goal-6",
    category: "자격증",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 0,
    dDay: 24,
    status: "notStarted",
  },
  {
    id: "goal-7",
    category: "자격증",
    title: "정보처리기사 자격증",
    targetScore: 85,
    maxScore: 100,
    periodStart: "2026년 5월 27일",
    periodEnd: "2026년 7월 14일",
    progress: 62,
    dDay: 24,
    status: "imminent",
  },
];
